runtime: php74

env_variables:
  APP_KEY: base64:4UvuWvuHiNxND7rSFAa4W1/iLjVErWL81Kt84PYY/UI=
  APP_DEBUG: false
  LOG_CHANNEL: stackdriver
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  CACHE_DRIVER: database
  SESSION_DRIVER: database
  DB_DATABASE: website
  DB_USERNAME: root
  DB_PASSWORD: 5YxXd6bE9qmP
  DB_SOCKET: "/cloudsql/wsb-trends:us-central1:wsb-trends"
